<h1>SoMaze</h1>
<p>SoMaze is a puzzle game created by <a href="http://evilmousestudios.com">Evil Mouse Studios</a> for use with cryptocurrencies such as <a href="http://dogecoin.com/">Dogecoin</a>.  It&#39;s kind of a mix between a maze, minesweeper, and Stratego.</p>
<h2>Gameplay</h2>
<p>There are basically two roles in SoMaze, that of the <em>Puzzle Creator</em> and that of the <em>Puzzle Solver</em>.</p>
<h5>Puzzle Creator</h5>
<ul>
<li>The Puzzle Creator first selects the size of the map they&#39;d like to create.  The maximum size is currently 25x25</li>
<li>After selecting the size for the map, the Creator then places traps around the map.</li>
<li>Some traps can be seen by the player (such as lava tiles), and some are hidden until activated by the player (such as mines).</li>
<li>After designing the map and placing the traps, fees are set.<ul>
<li>The Entrance Fee is the amount the Solver pays the Creator to attempt to solve the puzzle.  The Creator gets this entire fee regardless of if the Solver wins or not.</li>
<li>The Reward is the amount the Creator pays to the Solver upon successful completion of the puzzle.  The Creator will only pay this once.  Upon successful completion of the puzzle, the puzzle will be marked &quot;deactivated&quot; and will not be playable anymore.</li>
<li>The Creation Fee is an amount that is determined automatically based on the size of the map, the number of traps, and the type of traps.  Larger, more elaborate maps will have larger Creation Fees.  The Creation Fee is payed by the Creator once when creating the map, and again every time a Solver attempts to solve the puzzle.</li>
</ul>
</li>
<li>After all the fees are set, the Creator must play through his puzzle before it goes live.  This is to ensure that the puzzle is solvable.</li>
</ul>
<h5>Puzzle Solver</h5>
<ul>
<li>The Puzzle Solver selects the puzzle they&#39;d like to attempt from a list of all currently active puzzles.  Puzzles are given a difficulty rating to assist the player in choosing the puzzle they&#39;d like to play.</li>
<li>Once the player has selected a puzzle, they will be required to pay the Entrance Fee before starting.<ul>
<li><em>Note: The Creation Fee is paid by the Creator, NOT the Solver.</em></li>
</ul>
</li>
<li>The player will start at the entrance, and click one tile at a time until they reach the exit (or die).  Players are only able to move to adjecent tiles, and diagonal moves aren&#39;t allowed.</li>
<li>If the player encounters a trap, they will be shown what trap they hit, and what the effects of the trap were.</li>
<li>If the player dies before reaching the exit, no reward is given.</li>
<li>If the player reaches the exit alive, the Reward is given, and the puzzle is marked &quot;deactivated&quot; (preventing future play on that puzzle)</li>
</ul>
<h2>Tips</h2>
<ul>
<li>It&#39;s not a good idea to make your puzzle so difficult that it&#39;s almost impossible to beat.  This ends up costing you in the Creation Fee, and also discourages players from attempting it.</li>
<li>The best puzzles are ones that are inexpensive to attempt, have few traps, but are surprisingly difficult.</li>
<li>Keep in mind that even though a puzzle may SEEM impossible, the Creator has to beat it before they are allowed to submit it.</li>
</ul>
<h2>Rules</h2>
<ul>
<li>When creating a puzzle:<ul>
<li>The Entry Fee and Reward must both be greater than or equal to the Creation Fee.</li>
<li>The title and description must be at least three letters long (each).</li>
<li>You are only allowed to have 10 games running at once.</li>
<li>You must solve the puzzle before others can play it.</li>
<li>You may cancel a puzzle you&#39;ve created as long as no one has played it yet.</li>
</ul>
</li>
</ul>
<ul>
<li>When solving a puzzle:<ul>
<li>You are only allowed to have 1 game open at a time.</li>
<li>If multiple people solve a puzzle, only the first to do so receives the reward money (the game will automatically close after a successful solve).</li>
</ul>
</li>
</ul>
